apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: shujohns/weather
        ports:
        - containerPort: 3000