apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 3000
    name: wordpress
    targetPort: 3000
  type: ClusterIP
  selector:
    app: wordpress